name: Deploy to EC2 (Docker)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" | base64 --decode > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

          ssh-keyscan -H 13.62.55.194 >> ~/.ssh/known_hosts

          echo "ğŸ” SSH key fingerprint:"
          ssh-keygen -lf ~/.ssh/id_rsa

      - name: Deploy to EC2
        run: |
          ssh -i ~/.ssh/id_rsa \
              -o IdentitiesOnly=yes \
              -o StrictHostKeyChecking=yes \
              ubuntu@13.62.55.194 << 'EOF'
            set -e
            cd /home/ubuntu/cicd-pipeline
            git pull origin main

            docker stop cicd-backend || true
            docker rm cicd-backend || true

            docker build -t cicd-backend .
            docker run -d \
              --name cicd-backend \
              --restart always \
              -p 8000:8000 \
              cicd-backend
          EOF
