name: Deploy to EC2 (Docker)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" | base64 --decode > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H 13.62.55.194 >> ~/.ssh/known_hosts

      - name: Deploy to EC2
        run: |
          ssh ubuntu@13.62.55.194 << 'EOF'
            set -e

            echo "ðŸ“¦ Moving to project directory"
            cd /home/ubuntu/cicd-pipeline

            echo "ðŸ”„ Pulling latest code"
            git pull origin main

            echo "ðŸ›‘ Stopping old container (if exists)"
            docker stop cicd-backend || true
            docker rm cicd-backend || true

            echo "ðŸ³ Building Docker image"
            docker build -t cicd-backend .

            echo "ðŸš€ Running new container"
            docker run -d \
              --name cicd-backend \
              --restart always \
              -p 8000:8000 \
              cicd-backend

            echo "âœ… Deployment successful"
          EOF
