name: Deploy cicd-pipeline to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup SSH Agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: |
            ${{ secrets.EC2_SSH_KEY }}

      - name: Add EC2 host
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H 13.62.55.194 >> ~/.ssh/known_hosts

      - name: Deploy to EC2
        run: |
          ssh ubuntu@13.62.55.194 << 'EOF'
            set -e
            cd /home/ubuntu/cicd-pipeline
            git pull origin main

            docker stop cicd-backend || true
            docker rm cicd-backend || true

            docker build -t cicd-backend .
            docker run -d \
              --name cicd-backend \
              --restart always \
              -p 8000:8000 \
              cicd-backend
          EOF
